version: '3'
services:

  mysql:
    image: mysql
    ports:
      - "1800:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: MercadoLivre

volumes:
  mysql-volume:
